<!DOCTYPE html>
<html lang="en"><head>
<script src="chap_7_files/libs/clipboard/clipboard.min.js"></script>
<script src="chap_7_files/libs/quarto-html/tabby.min.js"></script>
<script src="chap_7_files/libs/quarto-html/popper.min.js"></script>
<script src="chap_7_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="chap_7_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="chap_7_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="chap_7_files/libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.24">

  <meta name="author" content="André Victor Ribeiro Amaral">
  <title>Survival Models (MATH3085/6143)</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="chap_7_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="chap_7_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="chap_7_files/libs/revealjs/dist/theme/quarto-e436bd4c930d147ec8018015d5404e9a.css">
  <link href="chap_7_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="chap_7_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="chap_7_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="chap_7_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Survival Models (MATH3085/6143)</h1>
  <p class="subtitle">Chapter 7: Survival Regression Models</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
<a href="https://www.avramaral.com/">André Victor Ribeiro Amaral</a> 
</div>
<div class="quarto-title-author-email">
<a href="mailto:a.v.ribeiro-amaral@soton.ac.uk">a.v.ribeiro-amaral@soton.ac.uk</a>
</div>
        <p class="quarto-title-affiliation">
            University of Southampton
          </p>
    </div>
</div>

  <p class="date">22/10/2025</p>
</section>
<section id="recap" class="slide level2">
<h2>Recap</h2>
<div class="justify">
<p>In the last chapter, we</p>
<ul>
<li><p><span class="alert"><strong>Defined the non-parametric MLE:</strong></span> we resolved the problem of the unbounded likelihood by constructing a the Non-Parametric Maximum Likelihood Estimator of the survival distribution based on a discrete distribution with mass only at the observed failure times.</p></li>
<li><p>Derived the <span class="alert"><strong>Kaplan-Meier estimator</strong></span> for the survival function <span class="math inline">\(\hat{S}(t)\)</span>.</p></li>
<li><p>Learned how to calculate the variance using Greenwood’s formula and how to use the <span class="alert">Nelson-Aalen estimator <span class="math inline">\(\hat{H}(t)\)</span></span> and its resulting <span class="alert">Fleming-Harrington survival curve</span> as alternatives to Kaplan-Meier.</p></li>
</ul>
</div>
</section>
<section>
<section id="chapter-7-survival-regression-models" class="title-slide slide level1 center">
<h1><span style="font-size: 42px; color: #131516; display: block; margin-bottom: -50px"><span class="secondary"><strong>Chapter 7:</strong></span> Survival Regression Models</span></h1>

</section>
<section id="introduction" class="slide level2">
<h2>Introduction</h2>
<div class="justify small-text">
<p>Commonly, when we observe (possibly censored) survival times <span class="math inline">\(t_1, \cdots ,t_n\)</span>, we also observe the values of <span class="math inline">\(k\)</span> other variables, <span class="math inline">\(x_1, \cdots ,x_k\)</span>, for each of the <span class="math inline">\(n\)</span> units of observation.</p>
<div style="margin-top: 20pt;">

</div>
<div class="fragment">
<p>Then, we drop the assumption that the survival time variables <span class="math inline">\(T_1, \cdots ,T_n\)</span> are identically distributed, and investigate how their distribution depends on the <span class="alert"><strong>explanatory variables</strong></span> (or <span class="alert"><strong>covariates</strong></span>) <span class="math inline">\(x_1, \cdots, x_k\)</span>.</p>
<div style="margin-top: 20pt;">

</div>
</div>
<div class="fragment">
<p>In a <span class="alert"><strong>regression model</strong></span>, we assume that the dependence of the distribution of <span class="math inline">\(T_i\)</span> on the values of <span class="math inline">\(x_1, \cdots, x_k\)</span> is through a regression function, which is typically assumed to have linear structure, as <span class="math display">\[
\eta_i=\beta_1 x_{i1}+\beta_2 x_{i2}+ \cdots +\beta_k x_{ik}=\sum_{j=1}^k x_{ij}\beta_j=\mathbf{x}_i^{\top}\boldsymbol{\beta}
\]</span> where <span class="math inline">\(\mathbf{x}_i=(x_{i1},x_{i2},\ldots ,x_{ik})^{\top}\)</span> is the <span class="math inline">\(k\)</span>-vector containing the values of <span class="math inline">\(x_1,\cdots,x_k\)</span> for unit <span class="math inline">\(i\)</span> and <span class="math inline">\(\boldsymbol{\beta}=(\beta_{1},\beta_{2},\ldots ,\beta_{k})^{\top}\)</span> is a <span class="math inline">\(k\)</span>-vector of regression parameters.</p>
</div>
</div>
</section>
<section id="example-leukaemia-as-in-chapter-2" class="slide level2">
<h2>Example: Leukaemia (as in <span class="secondary">Chapter 2</span>)</h2>
<div class="justify">
<p>Survival times are given for 33 patients who died from <span class="alert">acute myelogenous leukaemia</span>. In <code>R</code>, this can be found in the <code>leuk</code> object in the <code>MASS</code> package.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">as_tibble</span>(leuk)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 33 × 3
     wbc ag       time
   &lt;int&gt; &lt;fct&gt;   &lt;int&gt;
 1  2300 present    65
 2   750 present   156
 3  4300 present   100
 4  2600 present   134
 5  6000 present    16
 6 10500 present   108
 7 10000 present   121
 8 17000 present     4
 9  5400 present    39
10  7000 present   143
# ℹ 23 more rows</code></pre>
</div>
</div>
<p><code>leuk</code> is a data frame with columns: <code>wbc</code> (white blood count), <code>ag</code> (a test result, “present” or “absent”), and <code>time</code> (survival time in weeks).</p>
</div>
</section>
<section id="example-leukaemia-as-in-chapter-2-1" class="slide level2">
<h2>Example: Leukaemia (as in <span class="secondary">Chapter 2</span>)</h2>
<div class="justify small-text">
<p>Here, we have two potential explanatory variables, <code>wbc</code> and <code>ag</code>. As <code>ag</code> is a factor (a non-numerical variable) we transform it in the regression function to an indicator (dummy) variable or variables, for example <span class="math display">\[
1(\texttt{ag}~~\text{is present}) =
\left\{ \begin{array}{ll}
1 &amp; \text{if}~~\texttt{ag}~~\text{is present}\\
0 &amp; \text{if}~~\texttt{ag}~~\text{is absent}
\end{array}
\right.
\]</span></p>
<div style="margin-top: 40pt;">

</div>
<div class="fragment">
<p>Similarly <span class="alert"><strong>further explanatory variables may be created</strong></span> from the numeric covariate <code>wbc</code>, e.g.&nbsp;<span class="math inline">\(\texttt{wbc}^2\)</span> to investigate possible quadratic dependence.</p>
</div>
</div>
</section>
<section id="proportional-hazards-gap-on-page-59" class="slide level2">
<h2>Proportional hazards <span class="alert"><strong>(Gap on page 59)</strong></span></h2>
<div class="justify small-text">
<p>As was the case with homogeneous survival models in <span class="secondary"><strong>Chapter 6</strong></span>, we frequently want to investigate the dependence of <span class="math inline">\(T_i\)</span> on <span class="math inline">\(x_1, \cdots, x_k\)</span>, <span class="alert"><strong>without</strong></span> assuming a particular parametric family for <span class="math inline">\(f_{T_i}\)</span>.</p>
<div class="fragment">
<div style="margin-top: 60pt;">

</div>
<p>A <span class="alert"><strong>proportional hazards</strong></span> model (or Cox regression model) assumes that the hazard function for the survival variable corresponding to the <span class="math inline">\(i\)</span>-th unit is <span class="math display">\[
h_{T_i}(t)=\exp\left\{\mathbf{x}_i^{\top}\boldsymbol{\beta}\right\}\cdot h_0(t)
\]</span> where <span class="math inline">\(h_0\)</span> is called the <span class="alert"><strong>baseline hazard function</strong></span> and is not assumed to have a particular mathematical form.</p>
</div>
<div class="fragment">
<div style="margin-top: 60pt;">

</div>
<p>Hence, we model the effect of the explanatory variables on the distribution of <span class="math inline">\(T_i\)</span> as multiplying the baseline hazard by the exponentiated regression function, <span class="math inline">\(\exp\{\eta_i\}\)</span>.</p>
</div>
</div>
</section>
<section id="proportional-hazards-gap-on-page-60" class="slide level2">
<h2>Proportional hazards <span class="alert"><strong>(Gap on page 60)</strong></span></h2>
<div class="justify small-text">
<p>Equivalently, <span class="math display">\[
\begin{eqnarray*}
S_{T_i}(t) &amp; = &amp; \exp\left[ - \int_0^t h_{T_i}(s) \mathrm{d}s \right]\\
&amp; = &amp; \exp\left[ - \int_0^t \exp\left(\mathbf{x}_i^T\boldsymbol{\beta}\right) \cdot h_0(s)\mathrm{d}s \right]\\
&amp; = &amp; \exp\left[ - \int_0^t h_0(s)\mathrm{d}s \right]^{\exp\left(\mathbf{x}_i^{\top}\boldsymbol{\beta}\right)}\\
&amp; = &amp; S_0(t)^{\exp\left(\mathbf{x}_i^T\boldsymbol{\beta}\right)}
\end{eqnarray*}
\]</span> where <span class="math display">\[S_0(t) = \exp\left[ - \int_0^t h_0(s)\mathrm{d}s \right]\]</span> is the baseline survivor function.</p>
</div>
</section>
<section id="partial-likelihood-gap-on-page-61" class="slide level2">
<h2>Partial likelihood <span class="alert"><strong>(Gap on page 61)</strong></span></h2>
<div class="justify small-text fragment">
<p>We require to estimate the regression parameters <span class="math inline">\(\boldsymbol{\beta}\)</span> without specifying (or even estimating) the baseline hazard <span class="math inline">\(h_0\)</span> (so we cannot write down a likelihood, as <span class="math inline">\(f_{T_i}\)</span> and <span class="math inline">\(S_{T_i}\)</span> are not fully specified).</p>
<p>The <span class="alert"><strong>partial likelihood function</strong></span> is the joint probability of the observed data <span class="secondary"><strong>conditional on the observed failure times <span class="math inline">\(\{t_i: d_i=1\}\)</span></strong></span>.</p>
<p>Conditioning on <span class="math inline">\(\{t_i: d_i=1\}\)</span>, the partial likelihood reduces to the probability of the failures occurring in the order in which they were observed.</p>
<p>Let <span class="math inline">\(R_i\)</span> be the <span class="alert"><strong>risk set</strong></span> at <span class="math inline">\(t_i\)</span>, that is <span class="math display">\[
R_i=\{j:t_j\ge t_i\}
\]</span> the units with failure or censoring times at, or after, <span class="math inline">\(t_i\)</span>. Then, <span class="math display">\[
\mathbb{P}(T_j\in[t_i,t_i+\delta t]\,|\,j\in R_i)=h_{T_j}(t_i)\delta t=\exp\left(\mathbf{x}_j^{\top}\boldsymbol{\beta}\right)h_0(t_i)\delta t
\]</span> for some (infinitesimally small) <span class="math inline">\(\delta t\)</span>.</p>
</div>
</section>
<section id="partial-likelihood-gap-on-page-61-1" class="slide level2">
<h2>Partial likelihood <span class="alert"><strong>(Gap on page 61)</strong></span></h2>
<div class="justify small-text">
<p>Therefore <span class="math display">\[
\mathbb{P}(\mbox{some } j\in R_i \mbox{ fails in } [t_i,t_i+\delta t])=\sum_{j\in R_i} \exp\left(\mathbf{x}_j^{\top}\boldsymbol{\beta}\right)h_0(t_i)\delta t+O(\delta t^2).
\]</span></p>
<p>Hence, <span class="math display">\[
\begin{eqnarray*}
\mathbb{P}(T_i\in [t_i,t_i+\delta t] \,|\, \mbox{some } j\in R_i \mbox{ fails in } [t_i,t_i+\delta t])&amp;&amp; = \\[3pt]
&amp;&amp;\hspace{-12cm}=\;\frac
{\exp\left(\mathbf{x}_i^T\boldsymbol{\beta}\right)h_0(t_i)\delta t}
{\sum_{j\in R_i} \exp\left(\mathbf{x}_j^T\boldsymbol{\beta}\right)h_0(t_i)\delta t+O(\delta t^2)}=\frac
{\exp\left(\mathbf{x}_i^T\boldsymbol{\beta}\right)}
{\sum_{j\in R_i} \exp\left(\mathbf{x}_j^T\boldsymbol{\beta}\right)+O(\delta t)}\\
\end{eqnarray*}
\]</span> and in the limit <span class="math inline">\(\delta t\to 0\)</span>, <span class="math display">\[
\mathbb{P}(i \mbox{ fails at } t_i \,|\, \mbox{some } j\in R_i \mbox{ fails at } t_i)
=\frac
{\exp\left(\mathbf{x}_i^{\top}\boldsymbol{\beta}\right)}
{\sum_{j\in R_i} \exp\left(\mathbf{x}_j^{\top}\boldsymbol{\beta}\right)}.
\]</span></p>
</div>
</section>
<section id="partial-likelihood-gap-on-page-61-2" class="slide level2">
<h2>Partial likelihood <span class="alert"><strong>(Gap on page 61)</strong></span></h2>
<div class="justify small-text">
<p>The <span class="alert"><strong>partial likelihood</strong></span> is therefore given by <span class="math display">\[
\begin{eqnarray*}
L(\boldsymbol{\beta})&amp;=&amp;\mathbb{P}(\mbox{failures occurred in observed order})\\[3pt]
&amp;=&amp;\prod_{i:d_i=1}
\mathbb{P}(i \mbox{ fails at } t_i \,|\, \mbox{some } j\in R_i \mbox{ fails at } t_i)\\[3pt]
&amp;=&amp;\prod_{i:d_i=1}\frac
{\exp\left(\mathbf{x}_i^{\top}\boldsymbol{\beta}\right)}
{\sum_{j\in R_i} \exp\left(\mathbf{x}_j^{\top}\boldsymbol{\beta}\right)},
\end{eqnarray*}
\]</span> which does not depend on the baseline hazard <span class="math inline">\(h_0\)</span>.</p>
</div>
</section>
<section id="tied-failure-times-gap-on-page-63" class="slide level2">
<h2>Tied failure times <span class="alert"><strong>(Gap on page 63)</strong></span></h2>
<div class="justify small-text fragment">
<p>Suppose two observations (for example <span class="math inline">\(i=1\)</span> and <span class="math inline">\(i=2\)</span>) have the same recorded failure time. Our definition of <span class="math inline">\(R_i=\{j:t_j\ge t_i\}\)</span> includes <span class="math inline">\(1\in R_2\)</span> and <span class="math inline">\(2\in R_1\)</span>, <span class="alert"><strong>both of which cannot be true</strong></span>.</p>
<div class="fragment">
<p>Different partial likelihoods arise from assuming</p>
<ul>
<li><span class="math inline">\(1\)</span> failed just before <span class="math inline">\(2\)</span> (so <span class="math inline">\(2\in R_1\)</span> but <span class="math inline">\(1\not\in R_2\)</span>).</li>
<li><span class="math inline">\(2\)</span> failed just before <span class="math inline">\(1\)</span> (so <span class="math inline">\(2\not\in R_1\)</span> but <span class="math inline">\(1\in R_2\)</span>).</li>
</ul>
<div style="margin-top: -15pt;">

</div>
</div>
<div class="fragment">
<p>The correct action is to <span class="alert"><strong>average over these two assumptions</strong></span>, so we replace the contributions of units <span class="math inline">\(i=1\)</span> and <span class="math inline">\(i=2\)</span> to the partial likelihood with <span class="math display">\[
\frac
{\exp\left(\mathbf{x}_1^{\top}\boldsymbol{\beta}\right)}
{\sum_{j\in R_1} \exp\left(\mathbf{x}_j^{\top}\boldsymbol{\beta}\right)}
\frac
{\exp\left(\mathbf{x}_2^{\top}\boldsymbol{\beta}\right)}
{\sum_{j\in R_2'} \exp\left(\mathbf{x}_j^{\top}\boldsymbol{\beta}\right)}
+
\frac
{\exp\left(\mathbf{x}_2^{\top}\boldsymbol{\beta}\right)}
{\sum_{j\in R_2} \exp\left(\mathbf{x}_j^{\top}\boldsymbol{\beta}\right)}
\frac
{\exp\left(\mathbf{x}_1^{\top}\boldsymbol{\beta}\right)}
{\sum_{j\in R_1'} \exp\left(\mathbf{x}_j^{\top}\boldsymbol{\beta}\right)}
\]</span> where <span class="math inline">\(R_1'=R_1\setminus\{2\}\)</span> and <span class="math inline">\(R_2'=R_2\setminus\{1\}\)</span>.</p>
</div>
<div class="fragment">
<p>The exact partial likelihood for tied failures times can be complicated if we have <span class="math inline">\(m&gt;2\)</span> tied failure times (<span class="math inline">\(m!\)</span> terms in the average). <span class="alert">There exist approximations to the likelihood (e.g.&nbsp;Breslow and Efron) in the case of tied failure times.</span></p>
</div>
</div>
</section>
<section id="estimation" class="slide level2">
<h2>Estimation</h2>
<div class="justify small-text">
<p>We estimate the regression parameters <span class="math inline">\(\boldsymbol{\beta}\)</span> using the values <span class="math inline">\(\hat{\boldsymbol{\beta}}\)</span> which <span class="alert">maximise the partial likelihood <span class="math inline">\(L(\boldsymbol{\beta})\)</span>, or <strong>partial log-likelihood</strong></span> <span class="math display">\[
\ell(\boldsymbol{\beta})=\sum_{i:d_i=1} \mathbf{x}_i^{\top}\boldsymbol{\beta}-
\sum_{i:d_i=1}\log\left[\sum_{j\in R_i} \exp\left(\mathbf{x}_j^{\top}\boldsymbol{\beta}\right)\right]
\]</span></p>
<div class="fragment">
<p>Maximisation is performed by solving (numerically) the simultaneous equations <span class="math display">\[
\frac{\partial}{\partial\beta_i} \ell(\boldsymbol{\beta})=0,\qquad i=1,\ldots ,k.
\]</span></p>
</div>
<div class="fragment">
<p>We also obtain <span class="math display">\[
\text{Var}(\hat\beta_i)\approx [I(\boldsymbol{\beta})^{-1}]_{ii}
\]</span> where <span class="math inline">\(I(\boldsymbol{\beta})\)</span> is the <span class="alert"><strong>observed information matrix</strong></span> defined by <span class="math display">\[
I(\boldsymbol{\beta})_{ij}=-\frac{\partial^2}{\partial\beta_i\partial\beta_j} \ell(\boldsymbol{\beta}).
\]</span></p>
</div>
</div>
</section>
<section id="confidence-intervals-gap-on-page-64" class="slide level2">
<h2>Confidence intervals <span class="alert"><strong>(Gap on page 64)</strong></span></h2>
<div class="justify small-text fragment">
<p>As with maximum likelihood, <span class="alert">maximum partial likelihood estimators have an asymptotic (<span class="math inline">\(n\to\infty\)</span>) Normal distribution</span>, so <span class="math display">\[
\frac{\hat\beta_i-\beta_i}{\text{se}(\hat\beta_i)}\sim \text{Normal}(0,1)
\]</span> can be used as an approximation in moderately large samples, where <span class="math display">\[
\text{se}(\hat\beta_i)^2= [I(\hat{\boldsymbol{\beta}})^{-1}]_{ii}
\]</span> is an estimate of the <span class="alert"><strong>(asymptotic) standard deviation of <span class="math inline">\(\hat{\beta_i}\)</span></strong></span>.</p>
<div style="margin-top: 10pt;">

</div>
<div class="fragment">
<p>Hence, a <span class="alert"><strong><span class="math inline">\((1-\alpha)\%\)</span> confidence interval</strong></span> for <span class="math inline">\(\beta_i\)</span> is <span class="math display">\[
[\hat\beta_i- z_{\left(1 - \frac{\alpha}{2}\right)} \cdot \text{se}(\hat\beta_i),~\hat\beta_i+z_{\left(1 - \frac{\alpha}{2}\right)} \cdot \text{se}(\hat\beta_i)]
\]</span></p>
<div style="margin-top: 30pt;">

</div>
</div>
<div class="fragment">
<p>In practice, <span class="alert">we rely on computer packages to compute standard errors.</span></p>
</div>
</div>
</section>
<section id="hypothesis-testing-gap-on-page-65" class="slide level2">
<h2>Hypothesis testing <span class="alert"><strong>(Gap on page 65)</strong></span></h2>
<div class="justify small-text fragment">
<p>In regression models, the hypothesis <span class="math inline">\(H_0:\beta_j=0\)</span> is equivalent to a model where the explanatory variable <span class="math inline">\(x_j\)</span> has no effect on survival (as its values are omitted from the regression function <span class="math inline">\(\mathbf{x}_i^{\top}\boldsymbol{\beta}\)</span>).</p>
<div style="margin-top: -10pt;">

</div>
<div class="fragment">
<p>We test this hypothesis, by noting that, under <span class="math inline">\(H_0:\beta_j=0\)</span>, we have the approximation <span class="math display">\[
\frac{\hat\beta_j - 0}{\text{se}(\hat\beta_j)} = \frac{\hat\beta_j}{\text{se}(\hat\beta_j)}\sim \text{Normal}(0,1).
\]</span></p>
<div style="margin-top: -10pt;">

</div>
</div>
<div class="fragment">
<p>So <span class="math inline">\(\hat\beta_j/\text{se}(\hat\beta_j)\)</span> is a test statistic whose values can be calibrated against a standard normal distribution. <span class="alert">For a <span class="math inline">\(\alpha\%\)</span> significance level, we reject <span class="math inline">\(H_0\)</span></span> when <span class="math display">\[
\left|\frac{\hat\beta_j}{\text{se}(\hat\beta_j)}\right|&gt;z_{\left(1 - \frac{\alpha}{2}\right)}.
\]</span></p>
<div style="margin-top: -10pt;">

</div>
</div>
<div class="fragment">
<p>We can also calculate a <span class="alert"><strong>p-value</strong></span> using (this is known as <span class="alert"><strong>Wald test</strong></span>) <span class="math display">\[
\text{p-value} = 2\cdot \left(1 - \mathbb{P}\left(Z \le \left|\frac{\hat\beta_j}{\text{se}(\hat\beta_j)}\right|\right)\right).
\]</span></p>
</div>
</div>
</section>
<section id="estimating-the-baseline-h_0t-h_0t-and-s_0t" class="slide level2">
<h2>Estimating the baseline <span class="math inline">\(h_0(t)\)</span>, <span class="math inline">\(H_0(t)\)</span> and <span class="math inline">\(S_0(t)\)</span></h2>
<div class="justify small-text">
<p>It is not necessary to estimate <span class="math inline">\(h_0\)</span> to answer interesting questions about which covariates affect survival time, and how they do so.</p>
<div class="fragment">
<p>However, as in the homogeneous model, <span class="alert">we can estimate the complete survival distribution nonparametrically</span>, by estimating the hazard function as if the underlying process was discrete.</p>
</div>
<div class="fragment">
<p>The <span class="alert"><strong>total failure probability</strong></span> (across the whole risk set) at failure time <span class="math inline">\(t_i\)</span> is <span class="math display">\[
\sum_{j\in R_i} h_{T_j}(t_i) \quad=\quad\sum_{j\in R_i} \exp(\mathbf{x}_j^{\top}\boldsymbol{\beta}) \cdot h_0(t_i)
\]</span> <!--
A Poisson approximation to the distribution of the number of failures at this time produces the estimator
$$
\sum_{j\in R_i} \exp(\mathbf{x}_j^{\top}\hat{\boldsymbol{\beta}}) \cdot \hat h_0(t_i) =d'_i \qquad\Rightarrow\qquad \hat h_0(t_i) =\frac{d'_i}{\sum_{j\in R_i} \exp(\mathbf{x}_j^{\top}\hat{\boldsymbol{\beta}})}
$$
where $d'_i$ is the total number of failures observed at $t_i$.
--></p>
</div>
<div class="fragment">
<p>An <span class="alert"><strong>estimate of the baseline hazard</strong></span> is given by <span class="math display">\[
\hat h_0(t_i) =\frac{d'_i}{\sum_{j\in R_i} \exp(\mathbf{x}_j^{\top}\hat{\boldsymbol{\beta}})},
\]</span> where <span class="math inline">\(d'_i\)</span> is the total number of failures observed at <span class="math inline">\(t_i\)</span>.</p>
</div>
</div>
</section>
<section id="estimating-the-baseline-h_0t-h_0t-and-s_0t-1" class="slide level2">
<h2>Estimating the baseline <span class="math inline">\(h_0(t)\)</span>, <span class="math inline">\(H_0(t)\)</span> and <span class="math inline">\(S_0(t)\)</span></h2>
<div class="justify small-text">
<p>As in the homogeneous case in <span class="secondary"><strong>Chapter 6</strong></span>, the discrete hazard estimates can be transformed into an estimate of the cumulative hazard or survival functions.</p>
<div class="fragment">
<p>Again, we let <span class="math inline">\(t'_1,\cdots ,t'_m\)</span> be the <span class="math inline">\(m\)</span> ordered distinct failure times with corresponding numbers of failures <span class="math inline">\(d'_1,\cdots ,d'_m\)</span>. Then <span class="math display">\[
\hat{H}_0(t)=\sum_{j=1}^i \hat h_0(t'_j)=\sum_{j=1}^i \frac{d'_j}{\sum_{k:t_k\ge t'_j} \exp(\mathbf{x}_k^{\top}\hat{\boldsymbol{\beta}})}\quad t\in[t'_i,t'_{i+1}), \quad i=0,\cdots ,m
\]</span></p>
</div>
<div class="fragment">
<p>(like the Nelson-Aalen estimator in the homogeneous case) and <span class="math display">\[
\hat{S}_0(t)= \prod_{j=1}^i\exp\left(-\frac{d'_j}{\sum_{k:t_k\ge t'_j} \exp(\mathbf{x}_k^{\top}\hat{\boldsymbol{\beta}})}\right)\qquad t\in[t'_i,t'_{i+1}), \quad i=0,\cdots ,m.
\]</span></p>
</div>
<div class="fragment">
<p>which implies <span class="math display">\[
\hat S_{T_i}(t)=\hat S_0(t)^{\exp\left(\mathbf{x}_i^{\top}{\hat{\boldsymbol{\beta}}}\right)}.
\]</span></p>
</div>
</div>
</section>
<section id="fitting-cox-models-using-r-gehan" class="slide level2">
<h2>Fitting Cox models using <code>R</code> (<code>gehan</code>)</h2>
<div class="justify small-text">
<p><span class="alert"><strong>Gehan data</strong></span>: remission times (in weeks) from a clinical trial of 42 leukaemia patients. Patients matched in pairs and randomised to 6-mercaptopurine (drug) or control (from <code>MASS</code> package).</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a><span class="fu">as_tibble</span>(gehan)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 42 × 4
    pair  time  cens treat  
   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;fct&gt;  
 1     1     1     1 control
 2     1    10     1 6-MP   
 3     2    22     1 control
 4     2     7     1 6-MP   
 5     3     3     1 control
 6     3    32     0 6-MP   
 7     4    12     1 control
 8     4    23     1 6-MP   
 9     5     8     1 control
10     5    22     1 6-MP   
# ℹ 32 more rows</code></pre>
</div>
</div>
</div>
</section>
<section id="fitting-cox-models-using-r-gehan-1" class="slide level2">
<h2>Fitting Cox models using <code>R</code> (<code>gehan</code>)</h2>
<div class="justify small-text">
<p>Using the <code>coxph()</code> and <code>Surv()</code> from the <code>survival</code> package, we can fit a Cox regression model for <code>gehan</code> as follows (using <code>treat</code> as covariate)</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>gehan.cox <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, <span class="at">event =</span> cens) <span class="sc">~</span> treat, <span class="at">data =</span> gehan)</span>
<span id="cb5-2"><a href=""></a><span class="fu">summary</span>(gehan.cox)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time, event = cens) ~ treat, data = gehan)

  n= 42, number of events= 30 

              coef exp(coef) se(coef)    z Pr(&gt;|z|)    
treatcontrol 1.572     4.817    0.412 3.81  0.00014 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

             exp(coef) exp(-coef) lower .95 upper .95
treatcontrol      4.82      0.208      2.15      10.8

Concordance= 0.69  (se = 0.041 )
Likelihood ratio test= 16.4  on 1 df,   p=5e-05
Wald test            = 14.5  on 1 df,   p=1e-04
Score (logrank) test = 17.2  on 1 df,   p=3e-05</code></pre>
</div>
</div>
</div>
</section>
<section id="fitting-cox-models-using-r-gehan-gap-on-page-68" class="slide level2">
<h2>Fitting Cox models using <code>R</code> (<code>gehan</code>) <span class="alert"><strong>(Gap on page 68)</strong></span></h2>
<div class="justify small-text fragment">
<p>The p-value associated with the treatment dummy variable is <span class="alert"><span class="math inline">\(1.4 \times 10^{-4}\)</span></span>, i.e.&nbsp;the treatment significantly affects survival time.</p>
<p>The estimated coefficient for treatment is <span class="alert"><span class="math inline">\(1.57213\)</span></span>. This means the control treatment is estimated to increase the hazard by a factor of <span class="alert"><span class="math display">\[
\exp \left(1.57213\right) = 4.81687
\]</span></span> relative to the 6-MP treatment. This estimate can be seen in the <code>R</code> output in the previous slide (along with a <span class="math inline">\(95\%\)</span> confidence interval).</p>
</div>
</section>
<section id="fitting-cox-models-using-r-gehan-2" class="slide level2">
<h2>Fitting Cox models using <code>R</code> (<code>gehan</code>)</h2>
<div class="justify small-text">
<p>The <code>R</code> code below create survival curves. The argument <code>newdata</code> allows us to specify values of the explanatory variables. In this case there is one explanatory variable which can take two values. So we compute two survival curves for those two values. For comparison, the <span class="alert">Kaplan Meier survival curves are also plotted</span> in grey.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a><span class="fu">par</span>(<span class="at">family =</span> <span class="st">"Latin Modern Roman 10"</span>, <span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">5.1</span>, <span class="fl">4.1</span>, <span class="fl">0.5</span>, <span class="fl">2.1</span>))</span>
<span id="cb7-2"><a href=""></a></span>
<span id="cb7-3"><a href=""></a>gehan.S  <span class="ot">&lt;-</span> <span class="fu">survfit</span>(gehan.cox, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">treat =</span> <span class="fu">c</span>(<span class="st">"control"</span>, <span class="st">"6-MP"</span>)))</span>
<span id="cb7-4"><a href=""></a>gehan.km <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, cens) <span class="sc">~</span> treat, <span class="at">data =</span> gehan)</span>
<span id="cb7-5"><a href=""></a></span>
<span id="cb7-6"><a href=""></a><span class="fu">plot</span>(gehan.S, <span class="at">ylab =</span> <span class="st">"Survival function"</span>, <span class="at">xlab =</span> <span class="st">"Time"</span>, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb7-7"><a href=""></a><span class="fu">lines</span>(gehan.km, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">col =</span> <span class="dv">8</span>)</span>
<span id="cb7-8"><a href=""></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">8</span>, <span class="dv">8</span>), </span>
<span id="cb7-9"><a href=""></a><span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"6-MP (Cox)"</span>,<span class="st">"Control (Cox)"</span>,<span class="st">"6-MP (KM)"</span>,<span class="st">"Control (KM)"</span>), <span class="at">cex =</span> <span class="fl">0.8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="chap_7_files/figure-revealjs/unnamed-chunk-4-1.png" class="quarto-figure quarto-figure-center" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="fitting-cox-models-using-r-leuk" class="slide level2">
<h2>Fitting Cox models using <code>R</code> (<code>leuk</code>)</h2>
<div class="justify small-text">
<p><span class="alert"><strong>Leukaemia data</strong></span>: survival times are given for 33 patients who died from <span class="alert">acute myelogenous leukaemia</span>. In <code>R</code>, this can be found in the <code>leuk</code> object in the <code>MASS</code> package.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a><span class="fu">as_tibble</span>(leuk)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 33 × 3
     wbc ag       time
   &lt;int&gt; &lt;fct&gt;   &lt;int&gt;
 1  2300 present    65
 2   750 present   156
 3  4300 present   100
 4  2600 present   134
 5  6000 present    16
 6 10500 present   108
 7 10000 present   121
 8 17000 present     4
 9  5400 present    39
10  7000 present   143
# ℹ 23 more rows</code></pre>
</div>
</div>
</div>
</section>
<section id="fitting-cox-models-using-r-leuk-1" class="slide level2">
<h2>Fitting Cox models using <code>R</code> (<code>leuk</code>)</h2>
<div class="justify small-text">
<p>Using the <code>coxph()</code> and <code>Surv()</code> from the <code>survival</code> package, we can fit a Cox regression model for <code>leuk</code> as follows (using a dummy variable for <code>ag</code> and a natural logarithm of <code>wbc</code> as covariates)</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a>leuk.cox <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time) <span class="sc">~</span> ag <span class="sc">+</span> <span class="fu">log</span>(wbc), <span class="at">data =</span> leuk)</span>
<span id="cb10-2"><a href=""></a><span class="fu">summary</span>(leuk.cox)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(time) ~ ag + log(wbc), data = leuk)

  n= 33, number of events= 33 

            coef exp(coef) se(coef)     z Pr(&gt;|z|)   
agpresent -1.069     0.343    0.429 -2.49   0.0128 * 
log(wbc)   0.368     1.444    0.136  2.70   0.0069 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

          exp(coef) exp(-coef) lower .95 upper .95
agpresent     0.343      2.913     0.148     0.796
log(wbc)      1.444      0.692     1.106     1.886

Concordance= 0.726  (se = 0.047 )
Likelihood ratio test= 15.6  on 2 df,   p=4e-04
Wald test            = 15.1  on 2 df,   p=5e-04
Score (logrank) test = 16.5  on 2 df,   p=3e-04</code></pre>
</div>
</div>
</div>
</section>
<section id="fitting-cox-models-using-r-leuk-gap-on-page-70" class="slide level2">
<h2>Fitting Cox models using <code>R</code> (<code>leuk</code>) <span class="alert"><strong>(Gap on page 70)</strong></span></h2>
<div class="justify small-text fragment">
<p>The significance of both explanatory variables is immediately obvious from the two p-values <span class="alert"><span class="math inline">\(0.01276\)</span></span> and <span class="alert"><span class="math inline">\(0.0068\)</span></span>. Strictly, we should formal model selection using either backwards or forwards selection, or using information criteria (see <code>MATH2010</code>).</p>
<p>The estimated coefficient for <span class="alert"><code>ag</code> is <span class="math inline">\(-1.06905\)</span></span>. This means <code>ag</code> being present is estimated to increase the hazard by a factor of <span class="alert"><span class="math display">\[
\exp \left(-1.06905\right) = 0.34333,
\]</span></span> relative to <code>ag</code> being absent, i.e.&nbsp;<code>ag</code> being present reduces the hazard.</p>
<p>The estimated coefficient for <span class="alert"><code>log(wbc)</code> is <span class="math inline">\(0.3677\)</span></span>. This <span class="math inline">\(\log(\text{wbc})\)</span> increasing by one unit is estimated to increase the hazard by a factor of <span class="alert"><span class="math display">\[
\exp\left(0.3677\right) = 1.44441,
\]</span></span> i.e.&nbsp;the higher the <code>wbc</code>, the higher the hazard.</p>
</div>
</section>
<section id="fitting-cox-models-using-r-leuk-2" class="slide level2">
<h2>Fitting Cox models using <code>R</code> (<code>leuk</code>)</h2>
<div class="justify small-text">
<p>Similarly to before, we can plot the estimated survival functions as follows.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a><span class="fu">par</span>(<span class="at">family =</span> <span class="st">"Latin Modern Roman 10"</span>, <span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">5.1</span>, <span class="fl">4.1</span>, <span class="fl">0.5</span>, <span class="fl">2.1</span>))</span>
<span id="cb12-2"><a href=""></a></span>
<span id="cb12-3"><a href=""></a>leuk.S <span class="ot">&lt;-</span> <span class="fu">survfit</span>(leuk.cox, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">ag  =</span> <span class="fu">c</span>(<span class="st">"present"</span>, <span class="st">"present"</span>, <span class="st">"absent"</span>, <span class="st">"absent"</span>), </span>
<span id="cb12-4"><a href=""></a>                                                 <span class="at">wbc =</span> <span class="fu">c</span>(<span class="dv">750</span>, <span class="dv">100000</span>, <span class="dv">750</span>, <span class="dv">100000</span>)))</span>
<span id="cb12-5"><a href=""></a></span>
<span id="cb12-6"><a href=""></a><span class="fu">plot</span>(leuk.S, <span class="at">ylab=</span> <span class="st">"Survival function"</span>, <span class="at">xlab =</span> <span class="st">"Time"</span>, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">8</span>, <span class="dv">8</span>))</span>
<span id="cb12-7"><a href=""></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">8</span>, <span class="dv">8</span>), </span>
<span id="cb12-8"><a href=""></a><span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Present (750)"</span>, <span class="st">"Present (100,000)"</span>,<span class="st">"Absent  (750)"</span>, <span class="st">"Absent  (100,000)"</span>), <span class="at">cex =</span> <span class="fl">0.8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="chap_7_files/figure-revealjs/unnamed-chunk-7-1.png" class="quarto-figure quarto-figure-center" width="576"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="checking-proportional-hazards-gap-on-page-72" class="slide level2">
<h2>Checking proportional hazards <span class="alert"><strong>(Gap on page 72)</strong></span></h2>
<div class="justify small-text">
<p>The assumption that covariates affect the response through proportional hazards is a strong one and <span class="alert"><strong>should be checked where possible</strong></span>.</p>
<div class="fragment">
<p>Recall that the survival function for <span class="math inline">\(T_i\)</span> can be written as <span class="math display">\[
S_{T_i}(t) = S_0(t)^{\exp \left( \mathbf{x}_i^{\top} \boldsymbol{\beta} \right)}.
\]</span> Taking the complementary log-log of both sides <span class="math display">\[
\begin{eqnarray*}
\log \left( - \log S_{T_i}(t) \right) &amp; = &amp; \log \left( - \exp \left( \mathbf{x}_i^{\top} \boldsymbol{\beta} \right) \log S_0(t) \right)\\
&amp; = &amp; \mathbf{x}_i^{\top} \boldsymbol{\beta} + \log\left(- \log S_0(t) \right).
\end{eqnarray*}
\]</span></p>
</div>
</div>
</section>
<section id="checking-proportional-hazards-gap-on-page-72-1" class="slide level2">
<h2>Checking proportional hazards <span class="alert"><strong>(Gap on page 72)</strong></span></h2>
<div class="justify small-text">
<p>Consider units <span class="math inline">\(i=1\)</span> and <span class="math inline">\(i=2\)</span> who differ only in the <span class="math inline">\(j\)</span>-th covariate. Then, <span class="math display">\[
\begin{eqnarray*}
\mathbf{x}_1^{\top} \boldsymbol{\beta} &amp; = &amp; \sum_{l=1}^k x_{1l}\beta_l =  x_{1j} \beta_j + \sum_{l \ne j} x_{1l}\beta_l\\
\mathbf{x}_2^{\top} \boldsymbol{\beta} &amp; = &amp; x_{2j} \beta_j+  \sum_{l \ne j} x_{2l}\beta_l
\end{eqnarray*}
\]</span> and <span class="math display">\[
\begin{eqnarray*}
\mathbf{x}_1^{\top} \boldsymbol{\beta} - \mathbf{x}_2^{\top} \boldsymbol{\beta} &amp;=&amp; x_{1j} \beta_j + \sum_{l \ne j} x_{1l}\beta_l - x_{2j} \beta_j-  \sum_{l \ne j} x_{2l}\beta_l\\
&amp; = &amp; (x_{1j}-x_{2j}) \cdot \beta_j
\end{eqnarray*}
\]</span> since <span class="math inline">\(\sum_{l \ne j} x_{1l}\beta_l = \sum_{l \ne j} x_{2l}\beta_l\)</span>.</p>
</div>
</section>
<section id="checking-proportional-hazards-gap-on-page-72-2" class="slide level2">
<h2>Checking proportional hazards <span class="alert"><strong>(Gap on page 72)</strong></span></h2>
<div class="justify small-text">
<p>Now <span class="math display">\[
\log \left( - \log S_{T_1}(t) \right) - \log \left( - \log S_{T_2}(t) \right) = (x_{1j}-x_{2j})\cdot \beta_j
\]</span> which does not depend on <span class="math inline">\(t\)</span>.</p>
<div class="fragment">
<p>That means if we were to plot <span class="math inline">\(\log \left( - \log S_{T_1}(t) \right)\)</span> and <span class="math inline">\(\log \left( - \log S_{T_2}(t) \right)\)</span> against <span class="math inline">\(t\)</span> we should get two parallel lines (if the assumption of proportional hazards is correct).</p>
</div>
<div class="fragment">
<p>Therefore, <span class="alert">a strategy for checking proportional hazards for covariate <span class="math inline">\(x_j\)</span> is</span></p>
<ul>
<li>Partition the data according to each distinct <span class="math inline">\(x_j\)</span> value observed</li>
<li>Fit a separate proportional hazards model (including all other covariates) to each subset</li>
<li>The estimates of <span class="math inline">\(\log \left( - \log S_{T}(t) \right)\)</span> for those separate models will be parallel if the proportional hazards assumption holds for <span class="math inline">\(x_j\)</span>.</li>
</ul>
</div>
<div class="fragment">
<p>Clearly this is only practical if <span class="math inline">\(x_j\)</span> has few distinct values (typically if <span class="math inline">\(x_j\)</span> is a factor).</p>
</div>
</div>
</section>
<section id="checking-proportional-hazards" class="slide level2">
<h2>Checking proportional hazards</h2>
<div class="justify small-text">
<p>The following <code>R</code> code produces the plot for the <code>gehan</code> dataset, where <span class="math inline">\(x_j\)</span> corresponds to <code>treat</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a>logmlog <span class="ot">&lt;-</span> <span class="cf">function</span>(x) { <span class="fu">log</span>(<span class="sc">-</span><span class="fu">log</span>(x)) }</span>
<span id="cb13-2"><a href=""></a></span>
<span id="cb13-3"><a href=""></a><span class="fu">par</span>(<span class="at">family =</span> <span class="st">"Latin Modern Roman 10"</span>, <span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">5.1</span>, <span class="fl">4.1</span>, <span class="fl">0.5</span>, <span class="fl">2.1</span>))</span>
<span id="cb13-4"><a href=""></a></span>
<span id="cb13-5"><a href=""></a>gehan.cox1 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, <span class="at">event =</span> cens) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> gehan[gehan<span class="sc">$</span>treat<span class="sc">==</span><span class="st">"control"</span>, ])</span>
<span id="cb13-6"><a href=""></a>gehan.cox2 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, <span class="at">event =</span> cens) <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> gehan[gehan<span class="sc">$</span>treat<span class="sc">==</span><span class="st">"6-MP"</span>,    ])</span>
<span id="cb13-7"><a href=""></a></span>
<span id="cb13-8"><a href=""></a>gehan.S1<span class="ot">&lt;-</span> <span class="fu">survfit</span>(gehan.cox1)</span>
<span id="cb13-9"><a href=""></a>gehan.S2<span class="ot">&lt;-</span> <span class="fu">survfit</span>(gehan.cox2)</span>
<span id="cb13-10"><a href=""></a></span>
<span id="cb13-11"><a href=""></a><span class="fu">plot</span>(gehan.S1, <span class="at">ylab=</span> <span class="st">"log(–log(S(t)))"</span>, <span class="at">xlab =</span> <span class="st">"Time"</span>, <span class="at">fun =</span> logmlog, <span class="at">conf.int =</span> <span class="cn">FALSE</span>, <span class="at">xlim =</span> <span class="fu">range</span>(gehan<span class="sc">$</span>time), <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb13-12"><a href=""></a><span class="fu">lines</span>(gehan.S2, <span class="at">fun =</span> logmlog, <span class="at">conf.int =</span> <span class="cn">FALSE</span>, <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb13-13"><a href=""></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>), <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Control"</span>, <span class="st">"6-MP"</span>), <span class="at">cex =</span> <span class="fl">0.8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="chap_7_files/figure-revealjs/unnamed-chunk-8-1.png" class="quarto-figure quarto-figure-center" width="480"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="checking-proportional-hazards-1" class="slide level2">
<h2>Checking proportional hazards</h2>
<div class="justify small-text">
<p>The following <code>R</code> code produces the plot for the <code>leuk</code> dataset, where <span class="math inline">\(x_j\)</span> corresponds to <code>ag</code>.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a>logmlog <span class="ot">&lt;-</span> <span class="cf">function</span>(x) { <span class="fu">log</span>(<span class="sc">-</span><span class="fu">log</span>(x)) }</span>
<span id="cb14-2"><a href=""></a></span>
<span id="cb14-3"><a href=""></a><span class="fu">par</span>(<span class="at">family =</span> <span class="st">"Latin Modern Roman 10"</span>, <span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">5.1</span>, <span class="fl">4.1</span>, <span class="fl">0.5</span>, <span class="fl">2.1</span>))</span>
<span id="cb14-4"><a href=""></a></span>
<span id="cb14-5"><a href=""></a>leuk.cox1 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time) <span class="sc">~</span> <span class="fu">log</span>(wbc), <span class="at">data =</span> leuk[leuk<span class="sc">$</span>ag <span class="sc">==</span> <span class="st">"absent"</span>,  ])</span>
<span id="cb14-6"><a href=""></a>leuk.cox2 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time) <span class="sc">~</span> <span class="fu">log</span>(wbc), <span class="at">data =</span> leuk[leuk<span class="sc">$</span>ag <span class="sc">==</span> <span class="st">"present"</span>, ])</span>
<span id="cb14-7"><a href=""></a></span>
<span id="cb14-8"><a href=""></a>leuk.S1 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(leuk.cox1, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">wbc =</span> <span class="fu">mean</span>(leuk<span class="sc">$</span>wbc)))</span>
<span id="cb14-9"><a href=""></a>leuk.S2 <span class="ot">&lt;-</span> <span class="fu">survfit</span>(leuk.cox2, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">wbc =</span> <span class="fu">mean</span>(leuk<span class="sc">$</span>wbc)))</span>
<span id="cb14-10"><a href=""></a></span>
<span id="cb14-11"><a href=""></a><span class="fu">plot</span>(leuk.S1, <span class="at">ylab =</span> <span class="st">"log(–log(S(t)))"</span>, <span class="at">xlab =</span> <span class="st">"Time"</span>, <span class="at">fun =</span> logmlog, <span class="at">conf.int =</span> <span class="cn">FALSE</span>, <span class="at">xlim =</span> <span class="fu">range</span>(leuk<span class="sc">$</span>time), <span class="at">lty =</span> <span class="dv">1</span>)</span>
<span id="cb14-12"><a href=""></a><span class="fu">lines</span>(leuk.S2, <span class="at">fun =</span> logmlog, <span class="at">conf.int =</span> <span class="cn">FALSE</span>, <span class="at">lty =</span> <span class="dv">2</span>)</span>
<span id="cb14-13"><a href=""></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Absent"</span>,<span class="st">"Present"</span>), <span class="at">cex =</span> <span class="fl">0.8</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="chap_7_files/figure-revealjs/unnamed-chunk-9-1.png" class="quarto-figure quarto-figure-center" width="480"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="af-and-parametric-models-gap-on-page-74" class="slide level2">
<h2>AF and parametric models <span class="alert"><strong>(Gap on page 74)</strong></span></h2>
<div class="justify small-text">
<p>We have focused on <span class="alert"><strong>semiparametric models</strong></span>, where the parameters <span class="math inline">\(\boldsymbol{\beta}\)</span> do <span class="alert"><strong>not</strong></span> completely specify the survival distribution.</p>
<div class="fragment">
<p>Fully parametric survival regression models do exist.</p>
<p>For example, consider a Weibull model, with <span class="math inline">\(T_i \sim \mathrm{Weibull}(\alpha, \theta_i)\)</span> (<span class="alert">we changed the scale parameter to <span class="math inline">\(\theta\)</span> to stop confusion with the <span class="math inline">\(\boldsymbol{\beta}\)</span> regression parameters</span>). The shape parameter <span class="math inline">\(\alpha\)</span> is the same for all units but the scale parameter <span class="math inline">\(\theta_i\)</span> is unit-specific depending on the explanatory variables as follows <span class="math display">\[
\begin{eqnarray*}
\theta_i &amp; = &amp; 1/\exp\left( \eta_i \right) = \exp\left( - \eta_i \right) = \exp\left( - \beta_0 - \mathbf{x}_i^{\top} \boldsymbol{\beta} \right) =  \exp\left( - \beta_0 - \sum_{j=1} x_{ij} \beta_j \right).
\end{eqnarray*}
\]</span> Now suppose <span class="math inline">\(T_{0i} \sim \mathrm{Weibull}(\alpha,1)\)</span>, then <span class="math display">\[
T_i = \exp \left(\eta_i \right)\cdot T_{0i},
\]</span> which can be shown using the properties in <span class="secondary"><strong>Section 4.2.1</strong></span>. The survival functions for <span class="math inline">\(T_{0i}\)</span> and <span class="math inline">\(T_i\)</span> are <span class="math display">\[
S_{T_{0i}}(t) = \exp \left( -t^\alpha \right) ~~~~~\text{and}~~~~~ S_{T_{i}}(t) = \exp \left( - \left( \exp\left(-\eta_i\right) t \right)^\alpha \right).
\]</span></p>
</div>
</div>
</section>
<section id="af-and-parametric-models-gap-on-page-74-1" class="slide level2">
<h2>AF and parametric models <span class="alert"><strong>(Gap on page 74)</strong></span></h2>
<div class="justify small-text">
<p>We see that the effect on the distribution of <span class="math inline">\(T_i\)</span> of the explanatory variables, through <span class="math inline">\(\eta_i\)</span> is to shrink (or stretch) the time axis, resulting in correspondingly longer (shorter) failure times.</p>
<p>This is called an <span class="alert"><strong>accelerated failure time (AFT) model</strong></span> (or accelerated life model), and is generally expressed through the survival function <span class="math display">\[
S_{T_i}(t)=S_0\left(t \cdot \exp (-\eta_i)\right)
\]</span> for some baseline survival function <span class="math inline">\(S_0\)</span>.</p>
<p>Although it is possible to consider semiparametric models (with <span class="math inline">\(S_0\)</span> not from a standard family) <span class="alert">it is more usual to use fully parametric accelerated failure models.</span></p>
</div>
</section>
<section id="families-of-accelerated-failure-models" class="slide level2">
<h2>Families of accelerated failure models</h2>
<div class="justify small-text">
<div style="margin-top: 40pt;">

</div>
<p><span class="math display">\[
T_i=\exp(\eta_i)\cdot T_{0i}~~~\qquad\mbox{where}\qquad~~~ \eta_i=\beta_0+\mathbf{x}_i^{\top}{\boldsymbol{\beta}}.
\]</span></p>
<div style="margin-top: 40pt;">

</div>
<table class="caption-top">
<colgroup>
<col style="width: 56%">
<col style="width: 6%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(T_{0i}\)</span></th>
<th></th>
<th><span class="math inline">\(T_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\mathrm{Exp}(1)\)</span></td>
<td></td>
<td><span class="math inline">\(\mathrm{Exp}(\exp[-\eta_i])\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathrm{Weibull}(\alpha, 1)\)</span></td>
<td></td>
<td><span class="math inline">\(\mathrm{Weibull}(\alpha, \exp[-\eta_i])\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mathrm{Loglogistic}(\alpha, 1)\)</span></td>
<td></td>
<td><span class="math inline">\(\mathrm{Loglogistic}(\alpha, \exp[-\eta_i])\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathrm{Lognormal}(0, \sigma^2)\)</span></td>
<td></td>
<td><span class="math inline">\(\mathrm{Lognormal}(\eta_i, \sigma^2)\)</span></td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="estimating-accelerated-failure-models" class="slide level2">
<h2>Estimating accelerated failure models</h2>
<div class="justify small-text">
<p>For any parametric <span class="alert"><strong>AFT model</strong></span>, we know the form of <span class="math inline">\(S_{T_i}\)</span> and <span class="math inline">\(f_{T_i}\)</span>, so we can write down the likelihood <span class="math display">\[
L(\theta)=\prod_{i:d_i=1} f_{T_i}(t_i;\theta)\prod_{i:d_i=0} S_{T_i}(t_i;\theta)
\]</span> where <span class="math inline">\(\theta\)</span> comprises the regression parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\boldsymbol{\beta}\)</span> which enter into the computation of <span class="math inline">\(\eta_i\)</span> and any other parameters, such as <span class="math inline">\(\alpha\)</span>.</p>
<div class="fragment">
<p>Estimation is performed by maximum likelihood, to obtain <span class="math inline">\((\hat\beta_0,\,\hat{\boldsymbol{\beta}})\)</span> etc. with standard errors computed in the usual way.</p>
<p><span class="alert">Maximisation must be done numerically</span> (e.g.&nbsp;using <code>R</code>).</p>
</div>
</div>
</section>
<section id="example-weibull-aft-model-gehan" class="slide level2">
<h2>Example: Weibull AFT model (<code>gehan</code>)</h2>
<div class="justify small-text">
<p>The <code>R</code> code below fits a <span class="alert"><strong>Weibull AFT model</strong></span> with a dummy variable for treatment.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a>gehan.wb <span class="ot">&lt;-</span> <span class="fu">survreg</span>(<span class="fu">Surv</span>(time, <span class="at">event =</span> cens) <span class="sc">~</span> treat, <span class="at">data =</span> gehan)</span>
<span id="cb15-2"><a href=""></a><span class="fu">summary</span>(gehan.wb)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
survreg(formula = Surv(time, event = cens) ~ treat, data = gehan)
              Value Std. Error     z       p
(Intercept)   3.516      0.252 13.96 &lt; 2e-16
treatcontrol -1.267      0.311 -4.08 4.5e-05
Log(scale)   -0.312      0.147 -2.12   0.034

Scale= 0.732 

Weibull distribution
Loglik(model)= -106.6   Loglik(intercept only)= -116.4
    Chisq= 19.65 on 1 degrees of freedom, p= 9.3e-06 
Number of Newton-Raphson Iterations: 5 
n= 42 </code></pre>
</div>
</div>
<div class="fragment">
<p>Confusingly, <code>R</code> uses the following parameterisation for the shape parameter <span class="math inline">\(\hat{\alpha} = \frac{1}{\mathtt{scale}}\)</span>.</p>
<p>The estimates are <span class="math inline">\(\hat{\beta}_0 = 3.516\)</span>, <span class="math inline">\(\hat{\beta}_1 = -1.267\)</span>, and <span class="math inline">\(\hat{\alpha} = 1.366\)</span>.</p>
<p>The estimate of <span class="math inline">\(\beta_1\)</span> is negative meaning the treatment control will increase the scale parameter <span class="math inline">\(\theta\)</span> and increase the hazard (all relative to the 6-MP treatment).</p>
</div>
</div>
</section>
<section id="example-weibull-aft-model-gehan-1" class="slide level2">
<h2>Example: Weibull AFT model (<code>gehan</code>)</h2>
<div class="justify small-text">
<p>The following <code>R</code> code plots the estimated Kaplan-Meier and Cox survival curves. It then adds estimated survival curves from the Weibull model using the <code>curve</code> function.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a><span class="fu">par</span>(<span class="at">family =</span> <span class="st">"Latin Modern Roman 10"</span>, <span class="at">mar =</span> <span class="fu">c</span>(<span class="fl">5.1</span>, <span class="fl">4.1</span>, <span class="fl">0.5</span>, <span class="fl">2.1</span>))</span>
<span id="cb17-2"><a href=""></a>gehan.wb <span class="ot">&lt;-</span> <span class="fu">survreg</span>(<span class="fu">Surv</span>(time, <span class="at">event =</span> cens) <span class="sc">~</span> treat, <span class="at">data =</span> gehan)</span>
<span id="cb17-3"><a href=""></a></span>
<span id="cb17-4"><a href=""></a>alpha         <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">/</span> gehan.wb<span class="sc">$</span>scale)</span>
<span id="cb17-5"><a href=""></a>theta.control <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="sc">-</span>gehan.wb<span class="sc">$</span>coefficients[<span class="dv">1</span>] <span class="sc">-</span> gehan.wb<span class="sc">$</span>coefficients[<span class="dv">2</span>])</span>
<span id="cb17-6"><a href=""></a>theta<span class="fl">.6</span>MP     <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="sc">-</span>gehan.wb<span class="sc">$</span>coefficients[<span class="dv">1</span>])</span>
<span id="cb17-7"><a href=""></a></span>
<span id="cb17-8"><a href=""></a><span class="fu">plot</span>(gehan.S, <span class="at">ylab =</span> <span class="st">"Survival function"</span>, <span class="at">xlab =</span> <span class="st">"Time"</span>, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb17-9"><a href=""></a><span class="fu">lines</span>(gehan.km, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>), <span class="at">col =</span> <span class="dv">8</span>)</span>
<span id="cb17-10"><a href=""></a><span class="fu">curve</span>(<span class="at">expr =</span> <span class="fu">exp</span>(<span class="sc">-</span>(theta.control <span class="sc">*</span> x) <span class="sc">^</span> alpha), <span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">35</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lty =</span> <span class="dv">4</span>)</span>
<span id="cb17-11"><a href=""></a><span class="fu">curve</span>(<span class="at">expr =</span> <span class="fu">exp</span>(<span class="sc">-</span>(theta<span class="fl">.6</span>MP <span class="sc">*</span> x) <span class="sc">^</span> alpha),     <span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">35</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">lty =</span> <span class="dv">4</span>)</span>
<span id="cb17-12"><a href=""></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">4</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">8</span>, <span class="dv">8</span>, <span class="dv">1</span>, <span class="dv">1</span>), <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Control (Cox)"</span>, <span class="st">"6-MP (Cox)"</span>, <span class="st">"Control (KM)"</span>, <span class="st">"6-MP (KM)"</span>, <span class="st">"Control (WB)"</span>, <span class="st">"6-MP (WB)"</span>), <span class="at">cex =</span> <span class="fl">0.6</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="chap_7_files/figure-revealjs/unnamed-chunk-11-1.png" class="quarto-figure quarto-figure-center" width="480"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="example-weibull-aft-model-leuk" class="slide level2">
<h2>Example: Weibull AFT model (<code>leuk</code>)</h2>
<div class="justify small-text">
<p>The <code>R</code> code below fits a <span class="alert"><strong>Weibull AFT model</strong></span> with a dummy variable for test result.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href=""></a>leuk.wb <span class="ot">&lt;-</span> <span class="fu">survreg</span>(<span class="fu">Surv</span>(time) <span class="sc">~</span> ag <span class="sc">+</span> <span class="fu">log</span>(wbc), <span class="at">data =</span> leuk)</span>
<span id="cb18-2"><a href=""></a><span class="fu">summary</span>(leuk.wb)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
survreg(formula = Surv(time) ~ ag + log(wbc), data = leuk)
              Value Std. Error     z       p
(Intercept)  5.8524     1.3227  4.42 9.7e-06
agpresent    1.0206     0.3781  2.70  0.0069
log(wbc)    -0.3103     0.1313 -2.36  0.0181
Log(scale)   0.0399     0.1392  0.29  0.7745

Scale= 1.04 

Weibull distribution
Loglik(model)= -146.5   Loglik(intercept only)= -153.6
    Chisq= 14.18 on 2 degrees of freedom, p= 0.00084 
Number of Newton-Raphson Iterations: 6 
n= 33 </code></pre>
</div>
</div>
</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="chap_7_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="chap_7_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="chap_7_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="chap_7_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="chap_7_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="chap_7_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="chap_7_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="chap_7_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="chap_7_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="chap_7_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: false,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>