---
title: "MATH3085/6143: Survival Models"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    from: markdown+emoji
---

Welcome to **[MATH3085/6143: Survival Models]{.attention}**! **MATH3085/6143** introduces the fundamental concepts and key issues in lifetime and time-to-event data analysis, with applications in areas such as actuarial practice, medical sciences, and demography. 

Note that **MATH3085** and **MATH6143** are double-badged. This means that the course content of the two modules is the same but some of the assessment differs.

The Panopto **recorded lectures** are available on [Blackboard](https://blackboard.soton.ac.uk/){target="_blank"} (links for [MATH3085](https://southampton.cloud.panopto.eu/Panopto/Pages/Sessions/List.aspx#folderID=c0426b53-926a-4cd9-8e56-b4a300d1b606){target="_blank"} and [MATH6143](https://southampton.cloud.panopto.eu/Panopto/Pages/Sessions/List.aspx#folderID=41cfdb95-af0d-4184-8620-b4a300d1c78f){target="_blank"}; note that you must be logged in to access them).

---

### :teacher: **Instructor**

This module will be taught by [Dr André Amaral](https://www.avramaral.com/){target="_blank"} ([a.v.ribeiro-amaral@soton.ac.uk](mailto:a.v.ribeiro-amaral@soton.ac.uk)).

For any queries, please see me during the office hours: **Friday, 14:00–16:00, Room 54/10007**.

---

### :pencil: **Assessment**

The basic module assessment breakdown is

1. 30% [data analysis project](project.html)
2. 70% written exam

The [data analysis project](project.html) consists of a series of tasks in which you will conduct survival analyses on the provided datasets using `R`. The project will be released in early December 2026, with detailed instructions and guidance provided towards the end of the term.

---

### :book: **Lecture Notes**  

Lecture notes are available in two formats:

1. <a href="/lecture_notes/skeleton.pdf" download>Skeleton notes</a>: containing omissions corresponding to mathematical details.
2. <a href="/lecture_notes/complete.pdf" download>Complete notes</a>: in which the previously omitted parts are included and highlighted in blue.

Students are encouraged to use whichever version of the notes they find most helpful to their learning.

---

### :ledger: **Syllabus**

The module content is structured into 16 chapters (with the corresponding slides updated throughout the term)

1.  [Introduction](/slides/_output/chap_1.html)
2.  [Statistical Models](/slides/_output/chap_2.html)
3.  [The Survival Distribution](/slides/_output/chap_3.html)
4.  [Distributions for Survival Models](/slides/_output/chap_4.html)
5.  [Survival models: parameter estimation](/slides/_output/chap_5.html)
6.  [Non-parametric Survival Estimation](/slides/_output/chap_6.html)
7.  [Survival Regression Models](/slides/_output/chap_7.html)
8.  [Multistate Survival Models](/slides/_output/chap_8.html)
9.  [Inference for Multistate Models](/slides/_output/chap_9.html)
10. [Modelling Human Lifetime](/slides/_output/chap_10.html)
11. The Life Table and Life Expectancy <!--(/slides/_output/chap_11.html)-->
12. Interpolating a Life Table
13. Life Table Models
14. Exposure to Risk
15. Comparing Mortality Rates
16. Graduation

These chapters can be divided into six parts (labelled A to F), each corresponding to a [problem sheet](/problem_sheets.html). The table below shows which chapters are included in each part.

:::{.small-text}
| Part | Chapters | Problem sheet |
|------|----------|---------------|
| A    | 1-4      | 1             |
| B    | 5-6      | 2             |
| C    | 7        | 3             |
| D    | 8-9      | 4             |
| E    | 10-13    | 5             |
| F    | 14-16    | 6             |
:::

---

### :calendar: **Tentative Schedule** 

MATH3085/6143 has been given a timetable with the following slots

:::{.small-text}
| Day       | Time       | Room   |
|-----------|------------|--------|
| Tuesday   | 16:00-18:00 | 02/1089 |
| Thursday  | 15:00-17:00 | 35/1001 |
:::

<div style="margin-top: 25pt;"></div>

Below is the **tentative** schedule for the module.   

:::{.small-text}
| Week | Friday (Session 11-12pm)  | Friday (Session 12-1pm)  | Friday (Session 4-5pm) | Friday (Session 5-6pm) |
| ---- | -------------------- | -------------------- | -------------------- | -------------------- | 
| 01   | Chapter 1            | Chapter 2            | Chapter 3            | Chapter 4 (part 1)   | 
| 02   | Chapter 4 (part 2)   | Problem Sheet 1      | Chapter 5 (part 1)   | Chapter 5 (part 2)   | 
| 03   | Chapter 6 (part 1)   | Chapter 6 (part 2)   | Chapter 6 (part 3)   | Problem Sheet 2 (part 1) | 
| 04   | Problem Sheet 2 (part 2) | Chapter 7 (part 1)   | Chapter 7 (part 2)   | Chapter 7 (part 3)   | 
| 05   | Problem Sheet 3      | Chapter 8 (part 1)   | Chapter 8 (part 2)   | Chapter 8 (part 3)   | 
| 06   | Chapter 8 (part 4)   | Chapter 9 (part 1)   | Chapter 9 (part 2)   | Chapter 9 (part 3)   |
| 07   | Problem Sheet 4      | Chapter 10           |                      |                      |
| 08   | Chapter 11 (part 1)  | Chapter 11 (part 2)  | Chapter 12 (part 1)  | Chapter 12 (part 2)  | 
| 09   | Chapter 13 (part 1)  | Chapter 13 (part 2)  | Chapter 13 (part 3)  | Chapter 13 (part 4)  | 
| 10   | Problem Sheet 5 (part 1) |   Problem Sheet 5 (part 2)| Chapter 14  |  Chapter 15          | 
| 11   | Chapter 16 (part 1)  | Chapter 16 (part 2)  | Problem Sheet 6 (part 1) | Problem Sheet 6 (part 2) | 
| 12   | Revision (part 1) |  Revision (part 2) |               |                      | 
:::

<!-- Weeks [1-7]{.inst1} will be taught by [Dr André Amaral]{.inst1}, and weeks [8-11 and 15]{.inst2} will be taught by [Dr Chao Zheng]{.inst2}. -->
